server:
    port: 8080

spring:
  cloud:
    gcp:
      credentials:
        location: file:src/main/resource/google.key
  security:
    oauth2:
      client:
        registration:
         google:
          redirectUri: "https://{baseHost}/login/oauth2/code/{registrationId}"
          clientId: <GOOGLE_OAUTH_CLIENT_ID>
          clientSecret: <GOOGLE_OAUTH_CLIENT_SECRET>
          scope:
           - email
           - profile
